---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  metadata:
  labels:
    app: heimdall
  name: system:heimdall
  annotations:
    cloud.rvu.ontology/relation.v1.is_part_of: "/rvu/airship/observability/alerting"
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  verbs:
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - list
  - watch
