apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

commonLabels:
  app: heimdall

resources:
- deployment.yaml
- serviceaccount.yaml

configMapGenerator:
- name: heimdall-templates
  files: 
  - templates/p99-deployment.tmpl
  - templates/p95-deployment.tmpl
  - templates/4xx-rate-deployment.tmpl
  - templates/5xx-rate-deployment.tmpl
  - templates/5xx-rate.tmpl
  - templates/replicas-availability-deployment.tmpl
