---
apiVersion: v1
kind: ServiceAccount
metadata:
  metadata: 
  labels:
    app: heimdall
  name: heimdall
  namespace: monitoring
  annotations:
    cloud.rvu.ontology/relation.v1.is_part_of: "/rvu/airship/observability/alerting"
